export type SalonRole = 'owner' | 'manager' | 'worker' | 'cashier';

export type UserStatus = 'pending_approval' | 'approved' | 'rejected' | 'suspended';

export interface UserAccount {
  id: string;
  name: string;
  email: string;
  role: SalonRole;
  status: UserStatus;
  phone?: string;
  cnic?: string;
  password_hash?: string;
  avatar_url?: string;
  created_at?: string;
}

export interface RoleNavTab {
  id?: string;
  role: SalonRole;
  tab_id: string;
  tab_name: string;
  is_enabled: boolean;
}

export interface RolePermissions {
  can_manage_billing: boolean;
  can_manage_expenses: boolean;
  can_manage_staff: boolean;
  can_manage_payroll: boolean;
  can_manage_day_closing: boolean;
  can_view_clients: boolean;
  can_edit_clients: boolean;
  can_manage_services: boolean;
  can_view_reports: boolean;
  can_edit_settings: boolean;
  can_manage_loyalty: boolean;
  can_manage_roles: boolean;
  can_manage_marketing: boolean;
}

export interface SalonSettings {
  id: string;
  salon_name: string;
  tagline: string;
  phone: string;
  email: string;
  address: string;
  currency_symbol: string;
  currency_code: string;
  tax_rate: number;
  receipt_header: string;
  receipt_footer: string;
  owner_whatsapp?: string;
  auto_day_closing_enabled?: boolean;
  auto_day_closing_time?: string; // '23:59'
  allow_quick_walkin?: boolean; // Owner toggle: Allow 1-tap quick walk-in on POS
  allow_staff_attendance?: boolean; // Owner toggle: Enable/Disable Staff Attendance tab
  staff_permissions?: {
    allow_price_override?: boolean;
    allow_manual_discount?: boolean;
    allow_expense_logging?: boolean;
    allow_view_all_commissions?: boolean;
    require_pin_for_void?: boolean;
    allow_client_editing?: boolean;
    allow_void_invoices?: boolean;
    allow_reports_viewing?: boolean;
    allow_ledger_access?: boolean;
  };
  daily_expense_quota?: number; // Owner daily expense budget limit in PKR (e.g. 5000)
  late_penalty_config?: LatePenaltyRuleConfig;
  owner_financial_targets?: {
    monthly_rent_target?: number;
    monthly_electricity_target?: number;
    monthly_utilities_target?: number;
    daily_sales_target?: number;
    monthly_net_profit_target?: number;
  };
  whatsapp_templates?: {
    booking_reminder?: string;
    thank_you?: string;
    punch_milestone?: string;
    closing_report?: string;
    staff_commission_slip?: string;
  };
}

export type StaffPayType = 
  | 'salary_only'              // Fixed monthly base salary (no commission)
  | 'commission_only'          // Percentage of all service revenue generated by them
  | 'individual_partnership'   // Chair share / Partnership percentage on their own work only
  | 'salary_plus_commission';  // Base salary + service commission percentage

export interface StaffMember {
  id: string;
  name: string;
  phone: string;
  email?: string | null;
  cnic: string; // Pakistani National Identity Card number e.g. 42101-1234567-1
  role: 'owner' | 'manager' | 'senior_barber' | 'barber' | 'stylist' | 'therapist' | 'cashier';
  pay_type: StaffPayType;
  base_salary: number;
  commission_rate: number;
  partnership_percentage?: number; // e.g. 60 for 60% partnership split of own work
  station_fee?: number; // optional deduction for chair/product allocation
  specialization: string;
  is_active: boolean;
  avatar_url?: string | null;
  created_at?: string;
}

export interface ServiceCategoryRecord {
  id: string;
  name: string;
  description?: string | null;
  display_order?: number;
  created_at?: string;
}

export interface SalonService {
  id: string;
  name: string;
  category: string;
  price: number;
  duration_minutes?: number;
  description?: string | null;
  is_active: boolean;
  is_pinned?: boolean;
  created_at?: string;
}

export interface LoyaltyProgram {
  id: string;
  title: string;
  description: string;
  reward_name: string;
  reward_value: number; // in Rs. (e.g. 2500)
  required_visits: number; // e.g. 5
  min_spend_per_visit: number; // e.g. 500
  reward_type?: string;
  terms_conditions?: string;
  program_type?: 
    | 'milestone_visits'     // Digital Punch Card (e.g. 5th haircut free beard/facial)
    | 'duo_referral'         // Wingman Bonus (Bring a friend on Friday get 20% off)
    | 'offpeak_happy_hour'   // Slow-Day Booster (Tue/Wed afternoon free treatment)
    | 'product_bundle'       // Retail Add-On (Spend Rs. 4000 get styling wax at 50% off)
    | 'vip_station_pass'     // Executive Pass (Dedicated chair + beverage lounge)
    | 'custom';
  bonus_rate?: number; // percentage or multiplier e.g. 20% bonus credit
  is_active: boolean;
  created_at?: string;
}

export interface ClientRecord {
  id: string;
  name: string;
  phone: string;
  email?: string | null;
  notes?: string | null;
  preferred_staff_id?: string | null;
  preferred_staff_name?: string | null;
  loyalty_visits_count: number; // tracks qualifying visits >= Rs 500
  loyalty_free_facials_available: number; // earned free facials worth 2500 ready to redeem
  wallet_balance?: number; // Prepaid salon credits in PKR
  punch_card_stamps?: number; // 0 to 5
  vip_station_pass_active?: boolean;
  last_stamped_date?: string; // YYYY-MM-DD to enforce 1 stamp per day
  stamp_history?: StampHistoryRecord[];
  duo_referrals_count?: number;
  points_balance?: number;
  vip_tier?: 'Bronze' | 'Silver' | 'Gold' | 'Platinum' | string;
  birth_month?: number; // 1-12
  tags?: string[]; // e.g. ['VIP', 'Regular', 'Wedding Client']
  referred_by?: string | null;
  referral_code?: string;
  total_rewards_claimed: number;
  total_visits: number;
  total_spent: number;
  last_visit_date?: string | null;
  created_at?: string;
}

export interface InfluencerCollab {
  id: string;
  name?: string;
  handle?: string;
  platform?: 'instagram' | 'tiktok' | 'youtube' | string;
  followers?: string | number;
  deal_type?: 'barter_service' | 'paid_sponsorship' | 'barter' | string;
  service_provided?: string;
  discount_code?: string;
  status?: 'outreach' | 'confirmed' | 'content_live' | 'completed' | 'content_published' | 'visited' | 'scheduled' | string;
  clients_driven?: number;
  scheduled_date?: string;
  notes?: string;
  influencer_name?: string;
  social_handle?: string;
  followers_count?: number | string;
  barter_services?: string;
  deliverables_agreed?: string;
  promo_code_given?: string;
}

export interface SocialCalendarPost {
  id: string;
  day_of_week: string; // 'Monday' | 'Tuesday' etc.
  theme_title?: string;
  hook_idea?: string;
  suggested_format?: 'Reel' | 'Story' | 'Carousel' | 'Post' | string;
  caption_template?: string;
  hashtags?: string;
  theme?: string;
  post_type?: string;
  caption_outline?: string;
  is_published?: boolean;
}

export interface ReviewBounty {
  id: string;
  client_name: string;
  client_phone: string;
  platform: 'google_maps' | 'instagram_tag' | 'facebook' | 'google_review' | 'instagram_story' | string;
  status?: 'pending_verification' | 'reward_issued' | string;
  reward_status?: 'pending' | 'reward_issued' | 'rewarded' | 'pending_verification' | string;
  reward_amount: number; // Rs. 200 or 500
  review_rating?: number;
  proof_url?: string;
  verified_at?: string;
  created_at?: string;
}

export interface InvoiceItem {
  id?: string;
  service_id?: string | null;
  service_name: string;
  category: string;
  price: number; // can be custom edited per bill
  original_price?: number;
  staff_id?: string | null;
  staff_name?: string | null;
  commission_rate: number;
  commission_amount: number;
}

export type PaymentMethod = 'Cash' | 'Online Transfer' | 'Split' | 'Card' | 'Wallet';

export interface SplitPaymentDetail {
  method: 'Cash' | 'Online Transfer' | 'Card';
  amount: number;
}

export interface Invoice {
  id: string;
  invoice_number: string;
  client_id?: string | null;
  client_name: string;
  client_phone: string;
  client_email?: string | null;
  subtotal: number;
  discount_type: 'percentage' | 'fixed' | 'none';
  discount_value: number;
  discount_amount: number;
  loyalty_reward_applied?: string | null;
  loyalty_reward_discount?: number;
  points_redeemed?: number;
  points_discount_amount?: number;
  client_wallet_deducted?: number;
  vip_tier_discount_amount?: number;
  referral_code_used?: string | null;
  tax_rate: number;
  tax_amount: number;
  tip_amount: number;
  total_amount: number;
  payment_method: PaymentMethod;
  split_details?: SplitPaymentDetail[] | null;
  status: 'Completed' | 'Refunded' | 'Cancelled';
  notes?: string | null;
  created_by_role?: string;
  created_at: string;
  items: InvoiceItem[];
}

export interface StampHistoryRecord {
  id: string;
  client_id: string;
  client_name: string;
  date: string; // YYYY-MM-DD
  timestamp: string; // ISO string
  action: 'stamp_added' | 'stamp_removed' | 'stamp_edited' | 'reward_unlocked' | 'reward_redeemed';
  stamps_count: number; // resulting stamps count (0-5)
  previous_stamps?: number;
  new_stamps?: number;
  notes?: string;
  performed_by: string;
}

export type ExpenseCategory =
  | 'Salon Supplies & Products'
  | 'Rent & Lease'
  | 'Utilities (Electricity/Water)'
  | 'Equipment & Maintenance'
  | 'Tea, Water & Refreshments'
  | 'Staff Refreshments'
  | 'Marketing & Ads'
  | 'Miscellaneous';

export interface ExpenseRecord {
  id: string;
  title: string;
  category: ExpenseCategory | string;
  amount: number; // in PKR Rs.
  payment_mode: 'Cash' | 'Online Transfer' | 'Bank Card';
  expense_date: string;
  vendor?: string | null;
  notes?: string | null;
  receipt_ref?: string | null;
  logged_by?: string;
  created_at?: string;
  is_exceeded_expense?: boolean;
  quota_excess_amount?: number;
  exceeded_amount?: number;
}

export interface DayClosingRecord {
  id: string;
  closing_date: string;
  opening_cash: number;
  total_cash_sales: number;
  total_card_sales: number;
  total_online_sales: number;
  total_cash_expenses: number;
  expected_cash_in_drawer: number;
  actual_cash_counted: number;
  variance: number; // actual - expected
  notes?: string | null;
  closed_by: string;
  created_at?: string;
}

export type ChairStatus = 'Available' | 'Occupied' | 'Cleaning' | 'Reserved';

export interface SalonChair {
  id: number;
  name: string;
  status: ChairStatus;
  current_client_name?: string;
  current_service?: string;
  current_staff?: string;
  start_time?: string;
}

export type AppointmentStatus = 'Scheduled' | 'Confirmed' | 'In-Service' | 'Completed' | 'Cancelled';

export interface AppointmentRecord {
  id: string;
  client_name: string;
  client_phone: string;
  client_email?: string | null;
  service_id?: string | null;
  service_name: string;
  staff_id?: string | null;
  staff_name: string;
  appointment_date: string;
  appointment_time: string;
  chair_number?: number;
  duration_minutes?: number;
  status: AppointmentStatus;
  notes?: string | null;
  created_at?: string;
}

export type SalonAppointment = AppointmentRecord;

export interface MarketingCampaign {
  id: string;
  title: string;
  description?: string | null;
  discount_code?: string | null;
  discount_type: 'percentage' | 'fixed';
  discount_value: number;
  target_audience: 'all' | 'inactive_30d' | 'inactive_60d' | 'top_spenders' | 'vip';
  message_template: string;
  is_active: boolean;
  sent_count: number;
  created_at?: string;
}

export interface NoteChecklistItem {
  id: string;
  text: string;
  is_completed: boolean;
}

export interface OwnerNote {
  id: string;
  title: string;
  content: string;
  category: 'Operations' | 'Financial' | 'Staff' | 'Inventory' | 'Strategy' | 'Urgent' | 'General';
  is_pinned: boolean;
  checklist_items: NoteChecklistItem[];
  tags: string[];
  created_at?: string;
  updated_at?: string;
}

export type AttendanceStatus = 'Present' | 'Late' | 'Half Day' | 'Absent' | 'On Leave';

export interface LatePenaltyRuleConfig {
  grace_period_minutes: number; // e.g. 15 minutes grace
  penalty_mode: 'per_minute' | 'flat_per_late' | 'half_day_after_threshold' | 'three_lates_one_day';
  penalty_rate_per_minute: number; // e.g. 20 PKR/min
  flat_penalty_per_late: number; // e.g. 250 PKR per late day
  threshold_minutes_for_half_day: number; // e.g. 45 mins
}

export interface StaffAttendanceRecord {
  id: string;
  staff_id: string;
  staff_name: string;
  attendance_date: string; // YYYY-MM-DD
  clock_in?: string | null;
  clock_out?: string | null;
  status: AttendanceStatus;
  late_minutes: number;
  overtime_hours: number;
  is_paid_off?: boolean; // Owner marked penalty as paid off / waived
  waived_by?: string | null;
  waived_reason?: string | null;
  notes?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface AttendanceSalaryCalculation {
  staffId: string;
  staffName: string;
  payType: string;
  baseSalary: number;
  daysPresent: number;
  daysLate: number;
  daysHalfDay: number;
  daysAbsent: number;
  totalWorkingDays: number; // Total calendar days in that month (e.g. 30, 31, 28)
  perDayRate: number; // baseSalary / totalWorkingDays
  waivedLateCount: number;
  unwaivedLateCount: number;
  latePenaltyDeduction: number;
  attendanceAdjustedBase: number;
  commissionEarned: number;
  chairShare: number;
  stationFee: number;
  netPayout: number;
}

export interface StaffPermissionsConfig {
  can_give_discounts: boolean;
  can_record_expenses: boolean;
  can_view_owner_ledger: boolean;
  can_void_invoices: boolean;
  can_view_reports: boolean;
  can_edit_clients: boolean;
  can_adjust_stamps: boolean;
  can_manual_close_day: boolean;
}
